"""Serialization helpers for local GBS programs."""

from __future__ import annotations

import json
from typing import Any, Literal, cast

from jiuzhang.exceptions import InvalidParameterError
from jiuzhang.local.gbs._validation import optional_dependency
from jiuzhang.local.gbs.ir import GBSProgram, Operation

__all__ = ["dumps_ir", "loads_ir", "to_blackbird", "to_xir"]


def dumps_ir(program: GBSProgram, *, format: Literal["json", "blackbird", "xir"] = "json") -> str:
    """Serialize a local GBS program.

    Args:
        program: Program produced by ``GBSProgram``.
        format: Output format. Supported values are ``"json"``,
            ``"blackbird"``, and ``"xir"``.

    Returns:
        Serialized program text in the requested format.
    """
    if format == "json":
        return json.dumps(program.to_dict(), ensure_ascii=False, indent=2)
    if format == "blackbird":
        return to_blackbird(program)
    if format == "xir":
        return to_xir(program)
    raise InvalidParameterError("format must be 'json', 'blackbird', or 'xir'")


def loads_ir(payload: str) -> dict[str, Any]:
    """Load JSON local IR into a dictionary.

    Args:
        payload: JSON text generated by ``dumps_ir(..., format="json")``.

    Returns:
        Parsed local IR dictionary.
    """
    data = json.loads(payload)
    if not isinstance(data, dict) or data.get("schema") != "jiuzhang.local.gbs.v1":
        raise InvalidParameterError("unsupported local IR schema")
    return data


def to_blackbird(program: GBSProgram) -> str:
    """Serialize a local GBS program to Blackbird text and validate it.

    Args:
        program: Program produced by ``GBSProgram``.

    Returns:
        Blackbird-compatible program text.
    """
    blackbird = optional_dependency("blackbird")
    lines = [f"name {program.name}", "version 1.0", ""]
    for operation in program.operations:
        lines.extend(_operation_to_blackbird(operation))
    script = "\n".join(lines).rstrip() + "\n"
    return cast(str, blackbird.loads(script).serialize())


def to_xir(program: GBSProgram) -> str:
    """Serialize a local GBS program to XIR text.

    Args:
        program: Program produced by ``GBSProgram``.

    Returns:
        XIR-compatible program text.
    """
    xir = optional_dependency("xir")
    result = xir.Program()
    for operation in program.operations:
        result.add_statement(_operation_to_xir_statement(xir, operation))
    return cast(str, result.serialize())


def _operation_to_blackbird(operation: Operation) -> list[str]:
    if operation.name == "squeezing":
        return [f"Sgate({operation.params['r']}, {operation.params['phi']}) | {operation.modes[0]}"]
    if operation.name == "edge":
        left, right = operation.modes
        return [f"BSgate({operation.params['weight']}, 0.0) | [{left}, {right}]"]
    if operation.name == "measure_fock":
        return [f"MeasureFock() | {_format_modes(operation.modes)}"]
    if operation.name == "measure_threshold":
        return [f"MeasureThreshold() | {_format_modes(operation.modes)}"]
    raise InvalidParameterError(f"unsupported operation: {operation.name}")


def _operation_to_xir_statement(xir: Any, operation: Operation) -> Any:
    if operation.name == "squeezing":
        return xir.Statement(
            "squeezing", [operation.params["r"], operation.params["phi"]], operation.modes
        )
    if operation.name == "edge":
        return xir.Statement("edge", [operation.params["weight"]], operation.modes)
    if operation.name == "measure_fock":
        return xir.Statement("measure_fock", {"shots": operation.params["shots"]}, operation.modes)
    if operation.name == "measure_threshold":
        return xir.Statement(
            "measure_threshold", {"shots": operation.params["shots"]}, operation.modes
        )
    raise InvalidParameterError(f"unsupported operation: {operation.name}")


def _format_modes(modes: tuple[int, ...]) -> str:
    if len(modes) == 1:
        return str(modes[0])
    return "[" + ", ".join(str(mode) for mode in modes) + "]"
